[mozci]
verbose = 1
data_sources = ['treeherder_db', 'hgmo', 'adr']
maxdepth = 1

[mozci.cache]
default = "file"
retention = 1000

[mozci.cache.stores]
file = { driver = "file", path = "mozci_tests_cache" }

[adr]
verbose = 1

[adr.cache]
default = "file"
retention = 1000

[adr.cache.stores]
file = { driver = "file", path = "adr_tests_cache" }
